### ISSUE TITLE
Failed building wheel for cysignals m1 Mac

### ISSUE THREAD

**Issue by EHellebek** [sagemath/cysignals#173]
Hello all
I am trying to install cysignals using pip. I have tried both with PEP517, and after upgrading wheel, pip, cython and setuptools.

The error message is: 
```
Building wheels for collected packages: cysignals
  Building wheel for cysignals (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cysignals (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running bdist_wheel
      running build
      running build_py
      running configure
      autoconf
      make: autoconf: No such file or directory
      make: *** [configure] Error 1
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 193, in <module>
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 346, in run
          self.run_command("build")
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 172, in run
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/private/var/folders/4m/kwh91sq16438fytg_620zvy40000gn/T/pip-build-env-7hn_173s/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 133, in run
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', 'configure']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cysignals
Failed to build cysignals
ERROR: Could not build wheels for cysignals, which is required to install pyproject.toml-based projects
```

Any help will be greatly appreciated.

**Comment by tobiasdiez** [comment]
This should be fixed with #206 (at least autotools is no longer used now).
