### ISSUE TITLE
Problems building cysignal on Windows 11

### ISSUE THREAD

**Issue by Michdo93** [sagemath/cysignals#201]
Hi,

I received following trying to install `cysignals` in `Python 3.12.2` on `Windows 11`:

```
C:\Users\Admin> git clone https://github.com/sagemath/cysignals
Cloning into 'cysignals'...
remote: Enumerating objects: 2765, done.
remote: Counting objects: 100% (296/296), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 2765 (delta 242), reused 233 (delta 222), pack-reused 2469Rece

Receiving objects: 100% (2765/2765), 538.44 KiB | 1.90 MiB/s, done.
Resolving deltas: 100% (1542/1542), done.
PS C:\Users\Admin> cd cysignals
PS C:\Users\Admin\cysignals> pip install . --user
Processing c:\users\admin\cysignals
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cysignals
  Building wheel for cysignals (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cysignals (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      running build
      running build_py
      running configure
      autoconf
      autoheader
      checking for gcc... None
      checking whether the C compiler works... no
      configure: error: in `/c/Users/Admin/cysignals':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 204, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 183, in run
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\dist.py", line 967, in run_command
          super().run_command(command)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-4gia70qv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 146, in run
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['sh', 'configure', 'CC=None', 'CXX=None']' returned non-zero exit status 77.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cysignals
Failed to build cysignals
ERROR: Could not build wheels for cysignals, which is required to install pyproject.toml-based projects
PS C:\Users\Admin\cysignals> python --version
Python 3.12.2
```

Of course I tried it at first with

```
pip install cysignals
```

It is the same error.

In my `PATH` variable I set:

```
... C:\Program Files (x86)\Pari64-2-15-5;C:\cygwin64;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\TDM-GCC-64\bin;C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts;
```

Installing `Cython` worked well. And off course the `PATH` and installations in the paths above exists.

Thanks in advance
Michael

**Comment by saviornt** [comment]
Further than what I've gotten:

OS: Windows 11
Python Version: 3.12
Error:

```
Collecting git+https://github.com/sagemath/cysignals
  Cloning https://github.com/sagemath/cysignals to %APPDATA%\local\temp\pip-req-build-jb0598bm
  Running command git clone --filter=blob:none --quiet https://github.com/sagemath/cysignals '%APPDATA%\Local\Temp\pip-req-build-jb0598bm'
  Resolved https://github.com/sagemath/cysignals to commit 24d859f922fd2c105d3f90d95d386a1ed2354b5b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cysignals
  Building wheel for cysignals (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cysignals (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_py
      running configure
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cysignals
Failed to build cysignals
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cysignals)
```

I looked into the .toml file on github and I have both setuptools and Cython libraries installed already and I also tried installing the wheel library to no avail.
