### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by kiwifb** [sagemath/cysignals#22]
I was experimenting with my ebuild for gentoo and finally got to implement testing in a palatable way. The thing builds with python 3.4 but fails the doctesting
```
>>> Test phase: dev-python/cysignals-1.0_rc0
 * python2_7: running distutils-r1_run_phase python_test
 * python3_4: running distutils-r1_run_phase python_test
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 56, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGALRM)
Expected:
    AlarmInterrupt
Got:
    Traceback (most recent call last):
      File "src/cysignals/signals.pyx", line 151, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1631)
      File "src/cysignals/signals.pyx", line 95, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1000)
    cysignals.signals.AlarmInterrupt
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 71, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGSEGV)
Expected:
    SignalError: Segmentation fault
Got:
    Traceback (most recent call last):
      File "src/cysignals/signals.pyx", line 151, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1631)
      File "src/cysignals/signals.pyx", line 115, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1400)
    cysignals.signals.SignalError: b'Segmentation fault'
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 129, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGFPE)
Expected:
    FloatingPointError: Floating point exception
Got:
    Traceback (most recent call last):
      File "src/cysignals/signals.pyx", line 151, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1631)
      File "src/cysignals/signals.pyx", line 107, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1224)
    FloatingPointError: b'Floating point exception'
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 131, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGBUS, "CUSTOM MESSAGE")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest signals.pyx[12]>", line 1, in <module>
        sig_print_exception(signal.SIGBUS, "CUSTOM MESSAGE")
      File "src/cysignals/signals.pyx", line 148, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1604)
    TypeError: expected bytes, str found
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 133, in signals.pyx
Failed example:
    sig_print_exception(0)
Expected:
    SystemError: unknown signal number 0
Got:
    Traceback (most recent call last):
      File "src/cysignals/signals.pyx", line 151, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1631)
      File "src/cysignals/signals.pyx", line 117, in cysignals.signals.sig_raise_exception (build/src/cysignals/signals.c:1433)
    SystemError: unknown signal number 0
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 138, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGINT, "ignored")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest signals.pyx[14]>", line 1, in <module>
        sig_print_exception(signal.SIGINT, "ignored")
      File "src/cysignals/signals.pyx", line 148, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1604)
    TypeError: expected bytes, str found
**********************************************************************
File "/scratch2/portage/dev-python/cysignals-1.0_rc0/work/cysignals-1.0rc0/src/cysignals/signals.pyx", line 140, in signals.pyx
Failed example:
    sig_print_exception(signal.SIGALRM, "ignored")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest signals.pyx[15]>", line 1, in <module>
        sig_print_exception(signal.SIGALRM, "ignored")
      File "src/cysignals/signals.pyx", line 148, in cysignals.signals.sig_print_exception (build/src/cysignals/signals.c:1604)
    TypeError: expected bytes, str found
**********************************************************************
1 items had failures:
   7 of  22 in signals.pyx
***Test Failed*** 7 failures.
```
Some things are minor but some other are more "intriguing".

**Comment by jdemeyer** [comment]
I see two types of failure, both should be easy to fix:
1. `str` vs. `bytes`
2. different traceback display

It would be nice if somebody could setup Travis CI to test Python 3 too. Otherwise it's pointless to fix these issues.

**Comment by malb** [comment]
I've added testing for Python 3.4, adding other versions is straight forward, too.

**Comment by jdemeyer** [comment]
Thanks, I'm working on Python 3 now.
