### ISSUE TITLE
make distcheck failures 

### ISSUE THREAD

**Issue by vinklein** [sagemath/cysignals#72]
The target distcheck may fail on platform with previously installed cython package
```
$ make distcheck
autoconf
autoheader
...
setup.py:129: ImportWarning: Not importing directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython': missing __init__.py
  from Cython.Build.Dependencies import cythonize
Traceback (most recent call last):
...
ImportError: No module named Cython.Build.Dependencies
Makefile:110: recipe for target 'user-install' failed
make[1]: *** [user-install] Error 1

```

**Comment by jdemeyer** [comment]
Can you please provide the complete output of `make -k distcheck`

Also, what do you mean with "with previously installed cython package"?

**Comment by vinklein** [comment]
```
chmod go+rX-w -R .
umask 0022 && python setup.py sdist --formats=gztar
running sdist
running egg_info
writing cysignals.egg-info/PKG-INFO
writing top-level names to cysignals.egg-info/top_level.txt
writing dependency_links to cysignals.egg-info/dependency_links.txt
reading manifest file 'cysignals.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cysignals.egg-info/SOURCES.txt'
running check
creating cysignals-1.6.7
creating cysignals-1.6.7/.eggs
creating cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg
creating cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython
creating cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Runtime
creating cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
creating cysignals-1.6.7/cysignals.egg-info
creating cysignals-1.6.7/docs
creating cysignals-1.6.7/docs/source
creating cysignals-1.6.7/example
creating cysignals-1.6.7/src
creating cysignals-1.6.7/src/cysignals
creating cysignals-1.6.7/src/scripts
copying files to cysignals-1.6.7...
copying LICENSE -> cysignals-1.6.7
copying MANIFEST.in -> cysignals-1.6.7
copying Makefile -> cysignals-1.6.7
copying README.rst -> cysignals-1.6.7
copying VERSION -> cysignals-1.6.7
copying configure -> cysignals-1.6.7
copying configure.ac -> cysignals-1.6.7
copying rundoctests.py -> cysignals-1.6.7
copying setup.py -> cysignals-1.6.7
copying testgdb.py -> cysignals-1.6.7
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Runtime/refnanny.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Runtime
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/CConvert.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/CpdefEnums.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/CppConvert.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/MemoryView.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/TestCyUtilityLoader.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying .eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility/TestCythonScope.pyx -> cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython/Utility
copying cysignals.egg-info/PKG-INFO -> cysignals-1.6.7/cysignals.egg-info
copying cysignals.egg-info/SOURCES.txt -> cysignals-1.6.7/cysignals.egg-info
copying cysignals.egg-info/dependency_links.txt -> cysignals-1.6.7/cysignals.egg-info
copying cysignals.egg-info/top_level.txt -> cysignals-1.6.7/cysignals.egg-info
copying docs/Makefile -> cysignals-1.6.7/docs
copying docs/source/conf.py -> cysignals-1.6.7/docs/source
copying docs/source/crash.rst -> cysignals-1.6.7/docs/source
copying docs/source/index.rst -> cysignals-1.6.7/docs/source
copying docs/source/interrupt.rst -> cysignals-1.6.7/docs/source
copying docs/source/pselect.rst -> cysignals-1.6.7/docs/source
copying docs/source/pysignals.rst -> cysignals-1.6.7/docs/source
copying docs/source/sigadvanced.rst -> cysignals-1.6.7/docs/source
copying docs/source/sigerror.rst -> cysignals-1.6.7/docs/source
copying docs/source/signals.rst -> cysignals-1.6.7/docs/source
copying example/README -> cysignals-1.6.7/example
copying example/cysignals_example.pyx -> cysignals-1.6.7/example
copying example/setup.py -> cysignals-1.6.7/example
copying src/config.h.in -> cysignals-1.6.7/src
copying src/cysignals/__init__.py -> cysignals-1.6.7/src/cysignals
copying src/cysignals/alarm.pyx -> cysignals-1.6.7/src/cysignals
copying src/cysignals/debug.h.in -> cysignals-1.6.7/src/cysignals
copying src/cysignals/implementation.c -> cysignals-1.6.7/src/cysignals
copying src/cysignals/macros.h -> cysignals-1.6.7/src/cysignals
copying src/cysignals/memory.pxd -> cysignals-1.6.7/src/cysignals
copying src/cysignals/memory.pxi -> cysignals-1.6.7/src/cysignals
copying src/cysignals/pselect.pyx -> cysignals-1.6.7/src/cysignals
copying src/cysignals/pxi_warning.h -> cysignals-1.6.7/src/cysignals
copying src/cysignals/pysignals.pxd -> cysignals-1.6.7/src/cysignals
copying src/cysignals/pysignals.pyx -> cysignals-1.6.7/src/cysignals
copying src/cysignals/signals.pxd -> cysignals-1.6.7/src/cysignals
copying src/cysignals/signals.pxi -> cysignals-1.6.7/src/cysignals
copying src/cysignals/signals.pyx -> cysignals-1.6.7/src/cysignals
copying src/cysignals/struct_signals.h -> cysignals-1.6.7/src/cysignals
copying src/cysignals/tests.pyx -> cysignals-1.6.7/src/cysignals
copying src/cysignals/tests_helper.c -> cysignals-1.6.7/src/cysignals
copying src/scripts/cysignals-CSI -> cysignals-1.6.7/src/scripts
copying src/scripts/cysignals-CSI-helper.py -> cysignals-1.6.7/src/scripts
Writing cysignals-1.6.7/setup.cfg
Creating tar archive
removing 'cysignals-1.6.7' (and everything under it)
rm -rf dist/check
mkdir -p dist/check
cd dist/check && tar xzf ../cysignals-1.6.7.tar.gz
cd dist/check/cysignals-1.6.7 && ls -Ra1 >../dist0.ls
cd dist/check/cysignals-1.6.7 && make all
make[1]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
python setup.py build
running build
make[2]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
make[2]: 'configure' is up to date.
make[2]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing pari_init... -lpari
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking for backtrace... yes
checking whether PARI_SIGINT_block is declared... yes
checking for emms instruction... yes
configure: creating ./config.status
config.status: creating build/src/config.h
config.status: creating build/src/cysignals/debug.h
config.status: executing build/src/cysignals/__init__.pxd commands
generating build/lib.linux-x86_64-2.7/cysignals/__init__.pxd
Compiling src/cysignals/signals.pyx because it changed.
Compiling src/cysignals/pysignals.pyx because it changed.
Compiling src/cysignals/alarm.pyx because it changed.
Compiling src/cysignals/pselect.pyx because it changed.
Compiling src/cysignals/tests.pyx because it changed.
[1/5] Cythonizing src/cysignals/alarm.pyx
[2/5] Cythonizing src/cysignals/pselect.pyx
[3/5] Cythonizing src/cysignals/pysignals.pyx
[4/5] Cythonizing src/cysignals/signals.pyx
[5/5] Cythonizing src/cysignals/tests.pyx
running build_py
copying src/cysignals/__init__.py -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/signals.pxi -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/memory.pxi -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/signals.pxd -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/pysignals.pxd -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/memory.pxd -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/pxi_warning.h -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/struct_signals.h -> build/lib.linux-x86_64-2.7/cysignals
copying src/cysignals/macros.h -> build/lib.linux-x86_64-2.7/cysignals
copying build/src/cysignals/signals.h -> build/lib.linux-x86_64-2.7/cysignals
copying build/src/cysignals/debug.h -> build/lib.linux-x86_64-2.7/cysignals
running build_ext
building 'cysignals.signals' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/build
creating build/temp.linux-x86_64-2.7/build/src
creating build/temp.linux-x86_64-2.7/build/src/cysignals
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc/cysignals -Ibuild/src -Ibuild/src/cysignals -I/usr/include/python2.7 -c build/src/cysignals/signals.c -o build/temp.linux-x86_64-2.7/build/src/cysignals/signals.o
In file included from build/src/cysignals/signals.c:560:0:
build/src/cysignals/implementation.c:60:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 static cysigs_t cysigs;
 ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src/cysignals/signals.o -o build/lib.linux-x86_64-2.7/cysignals/signals.so -lpari
building 'cysignals.pysignals' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc/cysignals -Ibuild/src -Ibuild/src/cysignals -I/usr/include/python2.7 -c build/src/cysignals/pysignals.c -o build/temp.linux-x86_64-2.7/build/src/cysignals/pysignals.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src/cysignals/pysignals.o -o build/lib.linux-x86_64-2.7/cysignals/pysignals.so
building 'cysignals.alarm' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc/cysignals -Ibuild/src -Ibuild/src/cysignals -I/usr/include/python2.7 -c build/src/cysignals/alarm.c -o build/temp.linux-x86_64-2.7/build/src/cysignals/alarm.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src/cysignals/alarm.o -o build/lib.linux-x86_64-2.7/cysignals/alarm.so
building 'cysignals.pselect' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc/cysignals -Ibuild/src -Ibuild/src/cysignals -I/usr/include/python2.7 -c build/src/cysignals/pselect.c -o build/temp.linux-x86_64-2.7/build/src/cysignals/pselect.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src/cysignals/pselect.o -o build/lib.linux-x86_64-2.7/cysignals/pselect.so
building 'cysignals.tests' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc/cysignals -Ibuild/src -Ibuild/src/cysignals -I/usr/include/python2.7 -c build/src/cysignals/tests.c -o build/temp.linux-x86_64-2.7/build/src/cysignals/tests.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src/cysignals/tests.o -o build/lib.linux-x86_64-2.7/cysignals/tests.so -lpari
running build_scripts
creating build/scripts-2.7
copying and adjusting src/scripts/cysignals-CSI -> build/scripts-2.7
copying src/scripts/cysignals-CSI-helper.py -> build/scripts-2.7
changing mode of build/scripts-2.7/cysignals-CSI from 664 to 775
changing mode of build/scripts-2.7/cysignals-CSI-helper.py from 644 to 755
cd docs && make html
make[2]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7/docs'
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.3
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/2.7/objects.inv...
Starting new HTTPS connection (1): docs.python.org
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [100%] signals
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] signals
generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7/docs/source/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

Build finished. The HTML pages are in build/html.
make[2]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7/docs'
make[1]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
cd dist/check/cysignals-1.6.7 && make distclean
make[1]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
rm -rf docs/build
rm -rf build example/build example/*.cpp
rm -rf tmp
rm -rf autom4te.cache
rm -f config.log config.status
make[1]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
cd dist/check/cysignals-1.6.7 && ls -Ra1 >../dist1.ls
cd dist/check; diff -u dist0.ls dist1.ls || { echo >&2 "Error: distclean after all leaves garbage"; exit 1; }
cd dist/check/cysignals-1.6.7 && make check-user
make[1]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
rm -rf tmp/user
export PYTHONUSERBASE="`pwd`/tmp/user" && python setup.py install --user --single-version-externally-managed --record=/dev/null
running install
running build
make[2]: Entering directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
make[2]: 'configure' is up to date.
make[2]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing pari_init... -lpari
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking for backtrace... yes
checking whether PARI_SIGINT_block is declared... yes
checking for emms instruction... yes
configure: creating ./config.status
config.status: creating build/src/config.h
config.status: creating build/src/cysignals/debug.h
config.status: executing build/src/cysignals/__init__.pxd commands
generating build/lib.linux-x86_64-2.7/cysignals/__init__.pxd
setup.py:124: ImportWarning: Not importing directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7/.eggs/Cython-0.27.3-py2.7-linux-x86_64.egg/Cython': missing __init__.py
  from Cython.Build.Dependencies import cythonize
Traceback (most recent call last):
  File "setup.py", line 237, in <module>
    cmdclass=dict(build=build, build_py=build_py, install=install, bdist_egg=no_egg),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 119, in run
    dist.ext_modules[:] = self.cythonize(ext_modules)
  File "setup.py", line 124, in cythonize
    from Cython.Build.Dependencies import cythonize
ImportError: No module named Cython.Build.Dependencies
Makefile:103: recipe for target 'user-install' failed
make[1]: *** [user-install] Error 1
make[1]: Target 'check-user' not remade because of errors.
make[1]: Leaving directory '/home/vklein/odk/cysignals/dist/check/cysignals-1.6.7'
Makefile:113: recipe for target 'distcheck' failed
make: *** [distcheck] Error 2
```

> Also, what do you mean with "with previously installed cython package"?

I mean that the computer running {{{make distcheck}}} has a cython package installed.

**Comment by jdemeyer** [comment]
OK, you mean a **user** install of Cython?

**Comment by jdemeyer** [comment]
Can you check Cython master? I think that it should be fixed.

**Comment by vinklein** [comment]
Yes user install

**Comment by vinklein** [comment]
Same error on `make distcheck` with cython 0.28b

**Comment by jdemeyer** [comment]
Oops... I meant `cysignals` master.

**Comment by vinklein** [comment]
It's ok it is fixed : )
